apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /var/log/nginx
        name: shared-logs

  - name: sidecar-container
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sh"]
    args: ["-c", "while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]
    volumeMounts:
      - mountPath: /var/log/nginx
        name: shared-logs

  volumes:
  - name: shared-logs
    emptyDir: {}
