---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          args: ["--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi 
          volumeMounts:
            - name: mongodb-vol
              mountPath: /data/db         
      volumes:
        - name: mongodb-vol
          persistentVolumeClaim:
            claimName: mongodb-pvc
          
---
apiVersion: v1
kind: Service
metadata: 
  name: mongo-svc
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      protocol: TCP
  type: ClusterIP