apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
  labels:
    name: myapp
spec:
  containers:
  - name: print-env-container
    image: bash
    env:
      - name: GREETING
        value: "Welcome to"
      - name: COMPANY
        value: "Stratos"
      - name: GROUP
        value: "Ltd"
    command: ["echo"]
    args: ["$(GREETING) $(COMPANY) $(GROUP)"]
    ports:
      - containerPort: 80