---
#Kubernetes Cluster Role Object
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-manage-role
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io/v1"
    resources:
      - "*"
    verbs:
      - "create"
      - "delete"
      - "describe"
      - "get"
      - "list"
      - "patch"
      - "update"

---
#Kubernetes Role Binding Object

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-manage-binding
subjects:
- kind: User
  name: danish.hafeez
roleRef:
  kind: Role
  name: pod-manage-role
  apiGroup: rbac.authorization.k8s.io
