---
apiVersion: v1
kind: Secret
metadata:
  name: secret-pod-reference
type: Opaque
data:
  db_username: YWRtaW4K
  db_masterpassword: aGVsbG93b3JsZEAxMTIyCg==

--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: web
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: dbusername
          valueFrom:
            secretKeyRef:
              name: secret-pod-reference
              key: db_username
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: secret-pod-reference
              key: db_masterpassword
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
