---
apiVersion: v1
kind: Service
metadata:  
  name: jenkins-service
  namespace: jenkins
spec:
  selector:    
    app: jenkins
  type: NodePort
  ports:  
  - name: jenkins-server
    port: 8080
    targetPort: 8080
    nodePort: 30008
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
