---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard
  template:
    metadata:
      labels:
        app: grafana-dashboard
    spec:
      containers:
      - name: grafana-dashboard
        image: grafana/grafana:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard-svc
spec:
  selector:
    app: grafana-dashboard
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000

