---
apiVersion: v1
kind: Secret
metadata:
  name: imagepullsecret
  labels:
    docker-registry: loginCreds
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyTnlhWEIwTUd0cFpEcG9aV3hzYjNkdmNteGtRREV4TWpJPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Pod
metadata:
  name: monitoring-app
spec:
  containers:
    - name: monitoring-app
      image: script0kid/imagepullsecrets:monitoring.v1
      ports:
        - containerPort: 5000
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
  imagePullSecrets:
    - name: imagepullsecret




# kubectl create secret docker-registry regcred --docker-server=docker.io --docker-username=script0kid --docker-password=helloworld@1122 --docker-email=alam.akbar1989@gmail.com


