apiVersion: v1
kind: Pod
metadata:
  name: app-new
spec:
  containers:
  - name: app-new
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /app-new/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /app-new
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim