apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-eks-secret-manager-sa
  # namespace: example # Your prefered namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::489994096722:role/akbar-eks-secret-manager-role
