apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  # namespace: example # Your prefered namespace
spec:
  provider: aws
  secretObjects:
  - secretName: aws-sm
    type: Opaque
    data:
    - objectName: db_username
      key: mongo-username
    - objectName: db_password
      key: mongo-password
  parameters:     
    objects: | 
      - objectName: dev/mongodb-secrets 
        objectType: secretsmanager
        jmesPath:
          - path: MONGO_INITDB_ROOT_USERNAME
            objectAlias: db_username 
          - path: MONGO_INITDB_ROOT_PASSWORD 
            objectAlias: db_password
